spring.application.name=Dynamic_Quiz_Application-2

spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/mcq_quiz?sslMode=VERIFY_IDENTITY

spring.datasource.username=3UipzrmYve8kYnt.root

spring.datasource.password=y15sA4f2KDCWW2WW

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true