spring.application.name=Dynamic_Quiz_Application-2
spring.datasource.url=jdbc:mysql://localhost:3306/mcq_quiz
spring.datasource.username=root
spring.datasource.password=Naresh@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true